# Generated by Django 4.1.3 on 2022-11-09 09:53

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Rasifal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Rasifal_Desc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=200)),
                ('date', models.DateTimeField(verbose_name=datetime.datetime(2022, 11, 9, 9, 53, 8, 231422, tzinfo=datetime.timezone.utc))),
                ('rasi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rasifal.rasifal')),
            ],
        ),
    ]
