# Generated by Django 4.1.3 on 2022-11-09 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rasifal', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rasifal_desc',
            name='date',
            field=models.DateTimeField(),
        ),
    ]
