# Generated by Django 4.1.3 on 2022-11-09 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rasifal', '0002_alter_rasifal_desc_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rasifal_desc',
            name='date',
            field=models.DateField(),
        ),
    ]
